env:
  browser: true
  es2020: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
  - prettier
globels:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  complexity: ['error', 10]
  prettier/prettier:
    - error
